### ISSUE TITLE
Expose ability to pass in conn

### ISSUE THREAD

**Issue by jared2501** [strongswan/govici#21]
Currently, the only public API is `vici.WithSocketPath`. I'd like to be able to do `vici.WithConn`, and pass in an already constructed connection. Or, at the very least, be able to pass in a "network", "address", and net.Dialer. 

Use case: I'm using govici library and running strongswan in a couple docker containers. I have the vici interface configured to listen on a TCP port so that I can expose it from the container.

**Comment by jared2501** [comment]
cc @enr0n

**Comment by enr0n** [comment]
Fixed by https://github.com/strongswan/govici/commit/1904c5787ae68762dc07a9560c011d92d41b1dae
