### ISSUE TITLE
Possible Deadlock when Vici Socket Disappears

### ISSUE THREAD

**Issue by seglberg** [strongswan/govici#24]
We've been investigating possible deadlock when the Vici socket disappears (e.g. StrongSwan crashes or otherwise goes away). It appears deadlock happens under the following order of circumstances:

1. An event is registered with govici Session.
2. Socket goes away.
3. Close method is called on the govici Session.
4. Blocked indefinitely.

Deadlock does not occur unless an event is registered.

---

We've isolated it to a hard loop in the event listener once `vici: transport error: EOF` occurs.

Due to the `recv` method being called on the event listener repeatedly even after the first EOF occurs, the event channel (`el.ec`) fills up with 16 errors. Once this happens, the following code causes deadlock since the channel is now blocked and the mutex remains locked:

```
			el.emux.Lock()
			if len(el.events) > 0 {
				el.ec <- Event{err: err}
			}
			el.emux.Unlock()
```

Calling `session.Close` then remains blocked forever.

---

We were able to create a temporary patch by returning the EOF error directly from the `recv` method and in the event we receive an EOF, we return from the listener instead of continuing:

```
                        el.emux.Lock()
			if len(el.events) > 0 {
				el.ec <- Event{err: err}
			}
			el.emux.Unlock()

			if err == io.EOF {
				return
			}
```

---

Test Program:

```go
	session, err := vici.NewSession()
	if err != nil {
		panic(err)
	}

	err = session.Subscribe("child-updown")
	if err != nil {
		panic(err)
	}

	fmt.Println("About to Sleep: Stop StrongSwan Now")
	time.Sleep(5 * time.Second)
	fmt.Println("Waking Up, closing Session")

	err = session.Close()
	if err != nil {
		panic(err)
	}

	fmt.Println("Done")
```

**Comment by enr0n** [comment]
Nice catch. I'll write a regression test and patch soon.
