### ISSUE TITLE
why not has unload-cert method

### ISSUE THREAD

**Issue by dalekzhangdong** [strongswan/govici#26]
In https://www.strongswan.org/apidoc/md_src_libcharon_plugins_vici_README.html document, we have load-key() and unload_key() methods, and has load-cert() method also, but has't unload_cert() method , how can I delete the cert which load from vici protocol? Thank you!

**Comment by enr0n** [comment]
Hi @dalekzhangdong,

There is a `clear-creds` command that you *could* use. However, `clear-creds` will unload certificates, keys, and shared key data from the daemon (only those loaded over vici). This may be too heavy-handed for what you want.

Note that this repository is simply for the Go implementation of vici. If you would like to ask a follow up question on why there is no `unload-cert` vici command, please ask on IRC (irc://irc.freenode.net/strongswan) or the [strongswan-dev mailing list](https://lists.strongswan.org/mailman/listinfo/dev).

**Comment by dalekzhangdong** [comment]
Thanks a lot!
