### ISSUE TITLE
message: "empty message element" needs to be explicitly defined, documented, and verified

### ISSUE THREAD

**Issue by enr0n** [strongswan/govici#30]
Since go 1.13 introduced the `Value.IsZero` convenience method to the reflect package, I tried using this function instead of the [`emptyMessageElement` function](https://github.com/strongswan/govici/blob/master/vici/message.go#L764). I.e.,

```diff
diff --git a/vici/message.go b/vici/message.go
index 8daf7c9..7f2cf6e 100644
--- a/vici/message.go
+++ b/vici/message.go
@@ -829,7 +829,7 @@ func (m *Message) marshalFromStruct(rv reflect.Value) error {
 			continue
 		}
 
-		if emptyMessageElement(rfv) {
+		if rfv.IsZero() {
 			continue
 		}
```

However, this causes `TestMarshalBoolFalse` to fail...

```
=== RUN   TestMarshalBoolFalse
    TestMarshalBoolFalse: message_marshal_test.go:128: Marshalled boolean value is invalid.
        Expected: no
        Received: <nil>
```

...meaning our definition of an "empty" element is not consistent with the reflect package (42761e773b99861f23540cb632b13533a70e186f should have been a clue). As it stands, the `emptyMessageElement` is "correct" according to our test cases, but I am of the opinion this function should be consistent with `reflect.Value.IsZero` since it was originally written due to the absence of such a method in reflect.

I was looking into this code because I wanted to add an `omitempty` tag option to allow more flexibility to marshaling.

**Comment by enr0n** [comment]
@seglberg What are your thoughts on this? Was this intentional at the time it was written? Obviously if we changed this code to be consistent with (or use) `IsZero`, it would be a sort of API change.

**Comment by seglberg** [comment]
I think the inherent issue with `IsZero` is that we still want to serialize certain types of zero values, boolean being the prime example. Also 0 for integers, etc. So for the normal use case, we don't want to use it.

I guess it depends on what we want the behavior to be. If you're looking to add an `omitempty` and keep it similar to say, the json encoder, then you would marshal "null" values.

```golang
package main

import (
	"encoding/json"
	"fmt"
)

type Test struct {
	Bool        bool  `json:"bool"`
	BoolOmit    bool  `json:"boolOmit,omitempty"`
	BoolPtr     *bool `json:"boolPtr"`
	BoolPtrOmit *bool `json:"boolPtrOmit,omitempty"`
}

func main() {
	result, _ := json.Marshal(&Test{})
	fmt.Println(string(result))
}
```

```json
{"bool":false,"boolPtr":null}
```

So in this sense, we would remove the check for `emptyMessageElement` altogether and then only check `rfv.IsZero` if `omitempty` is set. 

This would make it more consistent with the json package and likely more consistent with what other users may expect _but_ the issue is that a `null` value doesn't semantically make as much sense for Message as it does with json.

**Comment by enr0n** [comment]
> I think the inherent issue with `IsZero` is that we still want to serialize certain types of zero values, boolean being the prime example. Also 0 for integers, etc. So for the normal use case, we don't want to use it.

Yes I agree. The reason I started looking into this part of the code (and adding `omitempty`) was because I wanted to make sure our unconditional use of `emptyMessageElement` was not too strict (because I thought it aligned more with `IsZero`). 

> I guess it depends on what we want the behavior to be. If you're looking to add an `omitempty` and keep it similar to say, the json encoder, then you would marshal "null" values.
> 
> ```go
> package main
> 
> import (
> 	"encoding/json"
> 	"fmt"
> )
> 
> type Test struct {
> 	Bool        bool  `json:"bool"`
> 	BoolOmit    bool  `json:"boolOmit,omitempty"`
> 	BoolPtr     *bool `json:"boolPtr"`
> 	BoolPtrOmit *bool `json:"boolPtrOmit,omitempty"`
> }
> 
> func main() {
> 	result, _ := json.Marshal(&Test{})
> 	fmt.Println(string(result))
> }
> ```
> 
> ```json
> {"bool":false,"boolPtr":null}
> ```
> 
> So in this sense, we would remove the check for `emptyMessageElement` altogether and then only check `rfv.IsZero` if `omitempty` is set.
> 
> This would make it more consistent with the json package and likely more consistent with what other users may expect _but_ the issue is that a `null` value doesn't semantically make as much sense for Message as it does with json.

Yes, that's a good point, it probably does not make sense to try and be *too* consistent with encoding/json et al. Maybe we just need to (1) explicitly define what constitutes an "empty message element", (2) document this definition thoroughly, and (3) ensure we have all the test cases to verify (1). 

Thanks for your input.
