### ISSUE TITLE
If charon is dead,  the vici session cannot be closed.

### ISSUE THREAD

**Issue by weixiaolan2019** [strongswan/govici#32]
Hi guys,

I have a bug, this is my code:

func TestFunc() {
        s, err := vici.NewSession()
	if err != nil {
	       fmt.Fprintf(os.Stderr, "vici NewSession failed!")
		return 
	}
	// Register event listener for 'ike-updown' events.
	if err := s.Listen(context.Background(), "ike-updown"); err != nil {
		 fmt.Fprintf(os.Stderr,"vici Listen failed!")
		s.Close()
		return 
	}
	for {
                e, err := s.NextEvent()
                if err != nil {
                        s.Close()
			fmt.Fprintf(os.Stderr,"vici is closed.")
			return 
		} else {
                        fmt.Fprintf(os.Stderr,"receive an event.")
                }
      }
}

    When the charon is alive,  everything goes well, but when charon is restarted, s.NextEvent() will get an error, if I call s.Close() to close the session, the function will be hung, but if I don't call s.Close(), the file handle opened cannot be closed.

    I debug the code, and find the s.Close is hung by chan.

func (s *Session) Close() error {
      ...............................................
	s.emux.RLock()
	if s.el != nil {
		**if err := s.el.Close(); err != nil {------------>The code is hung here**
			return err
		}
	}
	...........................................
	return nil
}

To find more  exact code in s.el.Close,
func (el *eventListener) Close() error {
	// Cancel the event listener context, and
	// wait for the destroy context to be done.
	el.cancel()
	**<-el.dctx.Done()   ---------------------------->this is the exact code line**
	return nil
}

In func s.Listen()

func (el *eventListener) listen(events []string) (err error) {
...............................
	go func() {
		defer el.destroy()
                for {
			...........................................................
			default:
				var e event
				_ = el.conn.SetReadDeadline(time.Now().Add(time.Second))

				p, err := el.recv()
				if err != nil {
					if ne, ok := err.(net.Error); ok && ne.Timeout() {
						continue
					}
					e.err = err
                                     // Send error event and continue in loop.
				**el.ec <- e ----------------------------->I find the code is hung here, so no one call  el.destroy(), that's why I cannot close the session.**
                                        continue
				}

				if p.ptype == pktEvent {
					e.msg = p.msg
					el.ec <- e
				}
			}
		}
	}()

	return nil
}

Best,

**Comment by seglberg** [comment]
Can you confirm the version of the library you are using? 

This looks to be the same as #24 (which was fixed in #25).
If you are not using 0.4.1 or newer, I would suggest upgrading and seeing if the issue persists.

**Comment by enr0n** [comment]
Seeing as this sample code uses `Session.Listen`, which was [changed to `Subscribe` in v0.4.0](https://github.com/strongswan/govici/blob/master/CHANGELOG.md#v040---2020-07-03), the fix for this (c46d9110f958661e4ebf1fba7914925fe3a5fd33) is not in your version of the package.

Please upgrade to at least v0.4.1 as @seglberg suggested.

**Comment by weixiaolan2019** [comment]
Thank you, I  get it.

**Comment by weixiaolan2019** [comment]
I have anther issue, this is the code:

func (t *transport) recv() (*packet, error) {
	buf := make([]byte, headerLength)

	t.conn.SetReadDeadline(time.Now().Add(time.Second * 20))

	_, err := t.conn.Read(buf)
	if err != nil {
		if ne, ok := err.(net.Error); ok && ne.Timeout() {
			return nil, ne
		}
		return nil, fmt.Errorf("%v: %v", errTransport, err)
	}
	pl := binary.BigEndian.Uint32(buf)
	//netbank.cn 
	**//need check the validity of buf length, because the length may be a very big number**
	_if pl > 1024*10 {
		fmt.Fprintf(os.Stderr, "vici recv len %v\n, %s", pl, debug.Stack())
		return nil, fmt.Errorf("vici error: recv wrong data len %v", pl)
	}_
	//netbank.cn 
	buf = make([]byte, int(pl))
	_, err = t.conn.Read(buf)
	if err != nil {
		return nil, fmt.Errorf("%v: %v", errTransport, err)
	}

	p := &packet{}
	err = p.parse(buf)
	if err != nil {
		return nil, err
	}

	return p, nil
}

**Comment by enr0n** [comment]
@weixiaolan2019 Please open a separate issue so we can keep things organized. :smile:
