### ISSUE TITLE
 The event-listener example has a panic

### ISSUE THREAD

**Issue by lixit** [strongswan/govici#35]
**Describe the bug**
This example has a panic [event-listener](https://github.com/strongswan/govici/blob/master/docs/getting_started.md#event-listener)
`panic: interface conversion: interface {} is nil, not *vici.Message`

**Version information**
- vici package version: v0.5.0
- StrongSwan version: 5.9.0

**Comment by enr0n** [comment]
Yes, that really should have a check on the type assertion. Will fix soon, thanks.

**Comment by enr0n** [comment]
Fixed by https://github.com/strongswan/govici/commit/beda77e501fe5d77bdef6dd1a6b3bfc6bf0131d2.
