### ISSUE TITLE
swanctl --load-creds equivalent in govici

### ISSUE THREAD

**Issue by nishantburte** [strongswan/govici#37]
I started looking at govici documentation  and sample code. I see that, it has implemented  some of the 'swanctl load-*' commands like load-conn. I could not find 'load-creds' equivalent command though.
Is this implemented already?

**Comment by enr0n** [comment]
In `swanctl`, the `load-creds` command is a [wrapper around a series of `load-key` and `load-cert` command requests](https://github.com/strongswan/strongswan/blob/master/src/swanctl/commands/load_creds.c#L891). I.e., there is no direct `load-creds` command in the vici protocol.

To create an equivalent, you may start by doing:

```go
type Cert struct {
        Flag string `vici:"flag"`
        Type string `vici:"type"`
        Data string `vici:"data"`
}

func LoadCert(s *vici.Session, cert *Cert) error {
        m, err := vici.MarshalMessage(cert)
        if err != nil {
                return err
        }

        _, err = s.CommandRequest("load-cert", m)

        return err
}

type Key struct {
        Type string `vici:"type"`
        Data string `vici:"data"`
}

func LoadKey(s *vici.Session, key *Key) error {
        m, err := vici.MarshalMessage(key)
        if err != nil {
                return err
        }

        _, err = s.CommandRequest("load-key", m)

        return err
}

func LoadCreds() {
        s, err := vici.NewSession()
        if err != nil {
                return err
        }
        defer s.Close()
        
        //  Iterate over directories with certs and keys, and make LoadCert and LoadKey calls...
}
```

Hope this helps.

**Comment by nishantburte** [comment]
thank you for the explanation. I don't need certificate.
I used "load-shared" instead of "load-key". It worked for my case.
How is 'load-shared' different from 'load-key', apart from obviously they take a little different input ? But essentially, both accept 'Type' and "data' parameters.

**Comment by enr0n** [comment]
They are different in the types of credentials they load: `load-shared` is used to load shared secrets, like a PSK or EAP secret, whereas `load-key` loads a private key.

**Comment by nishantburte** [comment]
thank you for the information
