### ISSUE TITLE
rekey fails and child SA disappears

### ISSUE THREAD

**Issue by nishantburte** [strongswan/govici#38]
I have started using govici a while ago.

I have noticed the default rekey time for child SA is 1h and connection is 4h. I noticed that, after 1h, child attempts to rekey and eventually fails.
To check this, I disabled connection rekey_time to 0 (so that rekey is disabled). for child SA, I set it to 180 seconds. 
My expectation is child SA will try to rekey once rekey timer reaches 0 and timer should again start from 180.
But after 180 seconds, rekeying process starts and it does not succeed.

In child SA section , I am only setting following fields:
mark_in, mark_out, start_action=start, local_ts, remote_ts, rekey_time=180.

Am I missing something for rekey to succeed?

Here is the 'ipsec statusall' output 1. just before rekey starts, 2. during rekeying process and 3. eventual failure.

1. just before rekey starts:
Security Associations (1 up, 0 connecting):
conn[1]: ESTABLISHED 2 minutes ago, 21.0.109.180[104.134.28.12]...35.242.127.5[35.242.127.5]
conn[1]: IKEv2 SPIs: f2103158733a4a12_i* 79e84ab3fc1b1427_r, rekeying disabled
conn[1]: IKE proposal: AES_GCM_8_128/PRF_AES128_XCBC/MODP_2048
connchild{1}:  INSTALLED, TUNNEL, reqid 1, ESP in UDP SPIs: c6a77bac_i 789afd30_o
connchild{1}:  AES_CBC_128/HMAC_SHA2_256_128, 0 bytes_i, 0 bytes_o, rekeying in 1 second
connchild{1}:   0.0.0.0/0 === 0.0.0.0/0

2. during rekeying
conn[1]: ESTABLISHED 2 minutes ago, 21.0.109.180[104.134.28.12]...35.242.127.5[35.242.127.5]
conn[1]: IKEv2 SPIs: f2103158733a4a12_i* 79e84ab3fc1b1427_r, rekeying disabled
conn[1]: IKE proposal: AES_GCM_8_128/PRF_AES128_XCBC/MODP_2048
connchild{1}:  INSTALLED, TUNNEL, reqid 1, ESP in UDP SPIs: c6a77bac_i 789afd30_o
connchild{1}:  AES_CBC_128/HMAC_SHA2_256_128, 0 bytes_i, 0 bytes_o, rekeying active
connchild{1}:   0.0.0.0/0 === 0.0.0.0/0

3. eventually after few seconds
conn[1]: ESTABLISHED 3 minutes ago, 21.0.109.180[104.134.28.12]...35.242.127.5[35.242.127.5]
conn[1]: IKEv2 SPIs: f2103158733a4a12_i* 79e84ab3fc1b1427_r, rekeying disabled
conn[1]: IKE proposal: AES_GCM_8_128/PRF_AES128_XCBC/MODP_2048
<No CHILDSA section here>  ====> why is this happening ?

**Comment by enr0n** [comment]
Hi @nishantburte,

This repository is only for the Go implementation of the vici protocol. For general strongSwan issues, please see https://wiki.strongswan.org/projects/strongswan/wiki/HelpRequests.
