### ISSUE TITLE
Event dispatching could silently drop messages if a receiver channel is full

### ISSUE THREAD

**Issue by fasilz** [strongswan/govici#45]
**Describe the bug**

The select pattern https://github.com/strongswan/govici/blob/afb1667b501cc8e51fc0baa42792784084e92232/vici/events.go#L140 will default to dropping a message if the receiver buffer is full. 

**To Reproduce**

```
// You can edit this code!
// Click here and start typing.
package main

import (
	"fmt"
	"sync"
	"time"
)

func main() {

	var c = make(chan int, 16)

	var wg sync.WaitGroup
	wg.Add(1)

	go func() {
		defer wg.Done()
		for {
			select {
			case v, ok := <-c:
				if !ok {
					return
				}
				fmt.Println(v)
				time.Sleep(time.Microsecond)
			}
		}
	}()

	for i := 0; i < 100; i++ {
		select {
		case c <- i:
		default:
			fmt.Printf("dropping %d\n", i)
		}

	}
	close(c)
	wg.Wait()
}
```

https://go.dev/play/p/hUQThyF0Tmf

**Expected behavior**

Message delivery should be reliant; current behavior could potentially cause a loss of events.  The previous implementation blocks rather than dropping messages. If this pattern is preferable for your implementation,  please provide some drop counters per event as exported field/function to be transparent on the loss of events.

**Screenshots**

**Version information**
[v0.6.0](https://github.com/strongswan/govici/releases/tag/v0.6.0)

**Additional context**

**Comment by enr0n** [comment]
Thanks for your bug report.

This is the intended behavior, and is noted in the `NotifyEvents` documenation: https://pkg.go.dev/github.com/strongswan/govici/vici#Session.NotifyEvents. Specifically, it is the caller's responsibility to allocate an appropriately sized channel. Do you have a specific use case where this API has been insufficient? 

I am not opposed to the idea of tracking event loss some how, but I don't have any immediate plans for this.

**Comment by fasilz** [comment]
Thank you for your response. I ended up implementing a heartbeat sender on the vici plugin itself so I can track message sequences and avoid quite losses.  This issue can be closed now.
