### ISSUE TITLE
Event notification channels are not closed when event transport recv() fails

### ISSUE THREAD

**Issue by daa** [strongswan/govici#46]
**Describe the bug**
Channels registered with ``NotifyEvents()`` are not closed when session transport ``recv()`` fails  thus making it impossible to detect session disconnect from strongSwan.

**To Reproduce**
Subscribe to some events, register notification channel with ``NotifyEvents()`` and then restart strongSwan.

**Expected behavior**
Registered notification channel should be closed or there must be some another way to detect session disconnect and consequent event listener loop stop.

**Screenshots**
N/A

**Version information**
- vici package version: 0.6.0
- StrongSwan version: 5.8.2

**Additional context**
``swanctl --monitor-sa`` doesn't detect strongSwan restarts too but Python implementation does. And as I understand old deprecated ``NextEvent()`` call handles this situation correctly.

**Comment by enr0n** [comment]
Thanks, this should definitely be fixed. I will look into it.

**Comment by enr0n** [comment]
@daa This should be fixed in master now. Feel free to test and let me know if any adjustments need to be made.

**Comment by daa** [comment]
Thank you very much! I've tested the patch and govici works as desired.
